{
  "openapi" : "3.0.0",
  "info" : {
    "contact" : {
      "email" : "Patrick.Sullivan@broadridge.com",
      "name" : "Patrick Sullivan",
      "url" : "https://sullivanpj.github.io/open-system/services/message"
    },
    "description" : "A collection of message APIs used by the Open System repository",
    "termsOfService" : "https://sullivanpj.github.io/open-system/services/message",
    "title" : "Message",
    "version" : "1.0"
  },
  "servers" : [ {
    "description" : "Local Development",
    "url" : "http://localhost:3000/messages"
  } ],
  "tags" : [ {
    "name" : "Message"
  } ],
  "paths" : {
    "/" : {
      "get" : {
        "description" : "An end point that returns the system's message literals to a client",
        "operationId" : "get-message-list",
        "parameters" : [ {
          "description" : "The type of message to return",
          "explode" : true,
          "in" : "query",
          "name" : "messageType",
          "required" : true,
          "schema" : {
            "default" : "FXL",
            "enum" : [ "FXL", "24  TRADING", "24 CORE", "24 GENERAL", "APPLICATION", "CLIENT", "TRADINGVALIDATION", "INTERNALVALIDATION" ],
            "example" : "FXL",
            "type" : "string"
          },
          "style" : "form"
        }, {
          "description" : "A specific message number to return",
          "explode" : true,
          "in" : "query",
          "name" : "messageNumber",
          "required" : false,
          "schema" : {
            "maximum" : 999999999,
            "minimum" : 0,
            "type" : "integer"
          },
          "style" : "form"
        }, {
          "description" : "User Id sending request",
          "in" : "header",
          "name" : "userId",
          "required" : true,
          "schema" : {
            "example" : "PSUL",
            "type" : "string"
          }
        } ],
        "responses" : {
          "200" : {
            "content" : {
              "application/json" : {
                "examples" : {
                  "Success Response" : {
                    "value" : [ {
                      "guid" : "123e4567-e89b-12d3-a456-426614174000",
                      "createdOn" : "2022-03-19 04:24:02.190",
                      "createdBy" : "PSUL",
                      "updatedOn" : "2022-10-12 14:01:13.000",
                      "updatedBy" : "PSUL",
                      "message" : "This message is displayed in the application",
                      "messageType" : "FXL",
                      "messageNumber" : 338296833,
                      "culture" : "EN-US"
                    } ]
                  }
                },
                "schema" : {
                  "items" : {
                    "$ref" : "#/components/schemas/Message"
                  },
                  "type" : "array"
                }
              }
            },
            "description" : "OK"
          },
          "401" : {
            "description" : "Unauthorized"
          },
          "404" : {
            "description" : "Not Found"
          },
          "500" : {
            "description" : "Internal Server Error"
          },
          "503" : {
            "description" : "Service Unavailable"
          }
        },
        "summary" : "Get Message List",
        "tags" : [ "Message" ]
      },
      "post" : {
        "description" : "Add new message record",
        "operationId" : "add-message",
        "parameters" : [ {
          "description" : "User Id sending request",
          "in" : "header",
          "name" : "userId",
          "required" : true,
          "schema" : {
            "example" : "PSUL",
            "type" : "string"
          }
        } ],
        "requestBody" : {
          "content" : {
            "application/json" : {
              "examples" : {
                "Sample Request" : {
                  "value" : {
                    "message" : "This message is displayed in the application",
                    "messageType" : "FXL",
                    "messageNumber" : 338296833,
                    "culture" : "EN-US"
                  }
                }
              },
              "schema" : {
                "$ref" : "#/components/schemas/MessageRequest"
              }
            },
            "application/javascript" : {
              "schema" : {
                "$ref" : "#/components/schemas/Message"
              }
            }
          },
          "description" : ""
        },
        "responses" : {
          "200" : {
            "content" : {
              "application/json" : {
                "examples" : {
                  "Success Response" : {
                    "value" : {
                      "guid" : "123e4567-e89b-12d3-a456-426614174000"
                    }
                  }
                },
                "schema" : {
                  "$ref" : "#/components/schemas/UpdateSuccessResponse"
                }
              }
            },
            "description" : "OK"
          },
          "401" : {
            "description" : "Unauthorized"
          },
          "404" : {
            "description" : "Not Found"
          },
          "500" : {
            "description" : "Internal Server Error"
          },
          "503" : {
            "description" : "Service Unavailable"
          }
        },
        "summary" : "Add Message",
        "tags" : [ "Message" ]
      }
    },
    "/{guid}" : {
      "delete" : {
        "description" : "Remove an existing message record",
        "operationId" : "delete-message",
        "parameters" : [ {
          "description" : "The records guid",
          "in" : "path",
          "name" : "guid",
          "required" : true,
          "schema" : {
            "example" : "123e4567-e89b-12d3-a456-426614174000",
            "format" : "uuid",
            "type" : "string"
          }
        }, {
          "description" : "User Id sending request",
          "in" : "header",
          "name" : "userId",
          "required" : true,
          "schema" : {
            "example" : "PSUL",
            "type" : "string"
          }
        } ],
        "responses" : {
          "200" : {
            "content" : {
              "application/json" : {
                "examples" : {
                  "Success Response" : {
                    "value" : {
                      "guid" : "123e4567-e89b-12d3-a456-426614174000"
                    }
                  }
                },
                "schema" : {
                  "$ref" : "#/components/schemas/UpdateSuccessResponse"
                }
              }
            },
            "description" : "OK"
          },
          "401" : {
            "description" : "Unauthorized"
          },
          "404" : {
            "description" : "Not Found"
          },
          "500" : {
            "description" : "Internal Server Error"
          },
          "503" : {
            "description" : "Service Unavailable"
          }
        },
        "summary" : "Remove Message",
        "tags" : [ "Message" ]
      },
      "get" : {
        "description" : "An end point that returns the system's message literals to a client",
        "operationId" : "get-message",
        "parameters" : [ {
          "description" : "The records guid",
          "in" : "path",
          "name" : "guid",
          "required" : true,
          "schema" : {
            "example" : "123e4567-e89b-12d3-a456-426614174000",
            "format" : "uuid",
            "type" : "string"
          }
        }, {
          "description" : "User Id sending request",
          "in" : "header",
          "name" : "userId",
          "required" : true,
          "schema" : {
            "example" : "PSUL",
            "type" : "string"
          }
        } ],
        "responses" : {
          "200" : {
            "content" : {
              "application/json" : {
                "examples" : {
                  "Success Response" : {
                    "value" : {
                      "guid" : "123e4567-e89b-12d3-a456-426614174000",
                      "createdOn" : "2022-03-19 04:24:02.190",
                      "createdBy" : "PSUL",
                      "updatedOn" : "2022-10-12 14:01:13.000",
                      "updatedBy" : "PSUL",
                      "message" : "This message is displayed in the application",
                      "messageType" : "FXL",
                      "messageNumber" : 338296833,
                      "culture" : "EN-US"
                    }
                  }
                },
                "schema" : {
                  "$ref" : "#/components/schemas/Message"
                }
              }
            },
            "description" : "OK"
          },
          "401" : {
            "description" : "Unauthorized"
          },
          "404" : {
            "description" : "Not Found"
          },
          "500" : {
            "description" : "Internal Server Error"
          },
          "503" : {
            "description" : "Service Unavailable"
          }
        },
        "summary" : "Get Message",
        "tags" : [ "Message" ]
      },
      "patch" : {
        "description" : "Update an existing message record",
        "operationId" : "update-message",
        "parameters" : [ {
          "description" : "The records guid",
          "in" : "path",
          "name" : "guid",
          "required" : true,
          "schema" : {
            "example" : "123e4567-e89b-12d3-a456-426614174000",
            "format" : "uuid",
            "type" : "string"
          }
        }, {
          "description" : "User Id sending request",
          "in" : "header",
          "name" : "userId",
          "required" : true,
          "schema" : {
            "example" : "PSUL",
            "type" : "string"
          }
        } ],
        "requestBody" : {
          "content" : {
            "application/json" : {
              "examples" : {
                "Sample Request" : {
                  "value" : {
                    "message" : "This message is displayed in the application",
                    "messageType" : "FXL",
                    "messageNumber" : 338296833,
                    "culture" : "EN-US"
                  }
                }
              },
              "schema" : {
                "$ref" : "#/components/schemas/MessageRequest"
              }
            }
          }
        },
        "responses" : {
          "200" : {
            "content" : {
              "application/json" : {
                "examples" : {
                  "Success Response" : {
                    "value" : {
                      "guid" : "123e4567-e89b-12d3-a456-426614174000"
                    }
                  }
                },
                "schema" : {
                  "$ref" : "#/components/schemas/UpdateSuccessResponse"
                }
              }
            },
            "description" : "OK"
          },
          "401" : {
            "description" : "Unauthorized"
          },
          "404" : {
            "description" : "Not Found"
          },
          "500" : {
            "description" : "Internal Server Error"
          },
          "503" : {
            "description" : "Service Unavailable"
          }
        },
        "summary" : "Update Message",
        "tags" : [ "Message" ]
      }
    }
  },
  "components" : {
    "parameters" : {
      "userId" : {
        "description" : "User Id sending request",
        "in" : "header",
        "name" : "userId",
        "required" : true,
        "schema" : {
          "example" : "PSUL",
          "type" : "string"
        }
      },
      "guid" : {
        "description" : "The records guid",
        "in" : "path",
        "name" : "guid",
        "required" : true,
        "schema" : {
          "example" : "123e4567-e89b-12d3-a456-426614174000",
          "format" : "uuid",
          "type" : "string"
        }
      }
    },
    "requestBodies" : { },
    "responses" : {
      "GetMessagesResponse" : {
        "content" : {
          "application/json" : {
            "examples" : {
              "Success Response" : {
                "value" : [ {
                  "guid" : "123e4567-e89b-12d3-a456-426614174000",
                  "createdOn" : "2022-03-19 04:24:02.190",
                  "createdBy" : "PSUL",
                  "updatedOn" : "2022-10-12 14:01:13.000",
                  "updatedBy" : "PSUL",
                  "message" : "This message is displayed in the application",
                  "messageType" : "FXL",
                  "messageNumber" : 338296833,
                  "culture" : "EN-US"
                } ]
              }
            },
            "schema" : {
              "items" : {
                "allOf" : [ {
                  "$ref" : "#/components/schemas/RecordBase"
                }, {
                  "$ref" : "#/components/schemas/Message"
                } ]
              },
              "type" : "array"
            }
          }
        },
        "description" : "Successful response to Get Messages end point"
      }
    },
    "schemas" : {
      "Message" : {
        "allOf" : [ {
          "$ref" : "#/components/schemas/RecordBase"
        }, {
          "$ref" : "#/components/schemas/MessageRequest"
        }, {
          "$ref" : "#/components/schemas/Message_allOf"
        } ],
        "description" : "A `Message` record returned from the server",
        "title" : "Message",
        "x-stoplight" : {
          "id" : "1uit484jxisd8"
        },
        "x-examples" : {
          "Sample Message" : {
            "guid" : "123e4567-e89b-12d3-a456-426614174000",
            "createdOn" : "2022-03-19 04:24:02.190",
            "createdBy" : "PSUL",
            "updatedOn" : "2022-10-12 14:01:13.000",
            "updatedBy" : "PSUL",
            "message" : "This message is displayed in the application",
            "messageType" : "FXL",
            "messageNumber" : 338296833,
            "culture" : "EN-US"
          }
        }
      },
      "MessageRequest" : {
        "description" : "An object sent to the server in a request to add a new or edit an existing `Message`. ",
        "properties" : {
          "message" : {
            "example" : "This message is displayed in the application",
            "type" : "string"
          },
          "messageType" : {
            "default" : "FXL",
            "enum" : [ "FXL", "24 CORE", "24 GENERAL", "APPLICATION", "CLIENT", "TRADINGVALIDATION", "INTERNALVALIDATION", "24 TRADING" ],
            "example" : "FXL",
            "type" : "string"
          },
          "messageNumber" : {
            "example" : 338296833,
            "maximum" : 999999999,
            "minimum" : 0,
            "type" : "integer"
          },
          "culture" : {
            "default" : "EN-US",
            "enum" : [ "EN-US" ],
            "example" : "EN-US",
            "type" : "string"
          }
        },
        "required" : [ "culture", "message", "messageType" ],
        "title" : "Message Request",
        "type" : "object",
        "x-stoplight" : {
          "id" : "1uit484jxisd8"
        },
        "x-examples" : {
          "Sample Message Request" : {
            "message" : "This message is displayed in the application",
            "messageType" : "FXL",
            "messageNumber" : 338296833,
            "culture" : "EN-US"
          }
        }
      },
      "UpdateSuccessResponse" : {
        "description" : "A response returned from the server when data is successfully updated",
        "example" : {
          "guid" : "123e4567-e89b-12d3-a456-426614174000"
        },
        "properties" : {
          "guid" : {
            "description" : "The `guid` associated with the record",
            "example" : "123e4567-e89b-12d3-a456-426614174000",
            "format" : "uuid",
            "title" : "Guid",
            "type" : "string",
            "x-stoplight" : {
              "id" : "rxw5bcg38wwhi"
            },
            "x-examples" : {
              "Sample Guid" : "123e4567-e89b-12d3-a456-426614174000"
            }
          }
        },
        "required" : [ "guid" ],
        "title" : "UpdateSuccessResponse",
        "type" : "object",
        "x-stoplight" : {
          "id" : "bnmwekvdvhi5z"
        },
        "x-examples" : {
          "Sample Response" : {
            "guid" : "123e4567-e89b-12d3-a456-426614174000"
          }
        }
      },
      "Guid" : {
        "description" : "The `guid` associated with the record",
        "example" : "123e4567-e89b-12d3-a456-426614174000",
        "format" : "uuid",
        "title" : "Guid",
        "type" : "string",
        "x-stoplight" : {
          "id" : "rxw5bcg38wwhi"
        },
        "x-examples" : {
          "Sample Guid" : "123e4567-e89b-12d3-a456-426614174000"
        }
      },
      "RecordBase" : {
        "description" : "The minimum model fields shared by all data stored in the database",
        "properties" : {
          "guid" : {
            "description" : "The `guid` associated with the record",
            "example" : "123e4567-e89b-12d3-a456-426614174000",
            "format" : "uuid",
            "title" : "Guid",
            "type" : "string",
            "x-stoplight" : {
              "id" : "rxw5bcg38wwhi"
            },
            "x-examples" : {
              "Sample Guid" : "123e4567-e89b-12d3-a456-426614174000"
            }
          },
          "createdOn" : {
            "format" : "date-time",
            "type" : "string"
          },
          "createdBy" : {
            "example" : "PSUL",
            "type" : "string"
          },
          "updatedOn" : {
            "format" : "date-time",
            "type" : "string"
          },
          "updatedBy" : {
            "example" : "PSUL",
            "type" : "string"
          }
        },
        "required" : [ "createdBy", "createdOn", "guid" ],
        "title" : "RecordBase",
        "type" : "object",
        "x-stoplight" : {
          "id" : "426vq5mn5uary"
        },
        "x-examples" : {
          "Sample Record" : {
            "guid" : "123e4567-e89b-12d3-a456-426614174000",
            "createdOn" : "2022-03-19 04:24:02.190",
            "createdBy" : "PSUL",
            "updatedOn" : "2022-10-12 14:01:13.000",
            "updatedBy" : "PSUL"
          }
        }
      },
      "Message_allOf" : {
        "properties" : {
          "messageNumber" : {
            "example" : 338296833,
            "maximum" : 999999999,
            "minimum" : 0,
            "type" : "integer"
          }
        },
        "required" : [ "messageNumber" ],
        "type" : "object",
        "example" : null
      }
    },
    "securitySchemes" : {
      "bearer-token" : {
        "description" : "A request header containing the JSON web token (JWT) provided by the IDM service in a cookie when the user signed into the application. This JWT contains the current user's encoded `SiteMinder` entitlements.",
        "scheme" : "bearer",
        "type" : "http"
      }
    }
  },
  "x-stoplight" : {
    "id" : "cd21s8nqejpjn"
  },
  "x-all-of-name" : "DTO_AllOf",
  "x-one-of-name" : "DTO_OneOf"
}
