{
  "openapi" : "3.0.0",
  "info" : {
    "contact" : {
      "email" : "Patrick.Joseph.Sullivan@protonmail.com",
      "name" : "Patrick Sullivan",
      "url" : "https://sullivanpj.github.io/open-system/services/message"
    },
    "description" : "A collection of APIs used to get and set reactions for an article/page ",
    "license" : {
      "name" : "BSD 2-Clause License",
      "url" : "https://opensource.org/licenses/BSD-2-Clause"
    },
    "termsOfService" : "https://sullivanpj.github.io/open-system/services/message",
    "title" : "Reaction",
    "version" : "1.0"
  },
  "servers" : [ {
    "description" : "Local Development",
    "url" : "http://localhost:3000/api"
  } ],
  "security" : [ {
    "bearer-token" : [ ]
  } ],
  "tags" : [ {
    "name" : "Reaction"
  } ],
  "paths" : {
    "/articles/{id}/reactions" : {
      "get" : {
        "description" : "An end point that returns the reactions for an article/page to a client",
        "operationId" : "get-reactions",
        "parameters" : [ {
          "description" : "The id of the article/page",
          "explode" : false,
          "in" : "path",
          "name" : "id",
          "required" : true,
          "schema" : {
            "type" : "string"
          },
          "style" : "simple"
        }, {
          "description" : "User Id sending request",
          "in" : "header",
          "name" : "userId",
          "required" : true,
          "schema" : {
            "example" : "PSUL",
            "type" : "string"
          }
        } ],
        "responses" : {
          "200" : {
            "content" : {
              "application/json" : {
                "examples" : {
                  "Success Example" : {
                    "value" : {
                      "guid" : "123e4567-e89b-12d3-a456-426614174000",
                      "createdOn" : "2022-03-19 04:24:02.190",
                      "createdBy" : "PSUL",
                      "updatedOn" : "2022-10-12 14:01:13.000",
                      "updatedBy" : "PSUL",
                      "articleId" : "home",
                      "reactions" : [ {
                        "type" : "LIKE",
                        "count" : 548
                      } ]
                    }
                  }
                },
                "schema" : {
                  "$ref" : "#/components/schemas/get_reactions_200_response"
                }
              }
            },
            "description" : "Successful response to Get Reactions end point"
          },
          "401" : {
            "content" : {
              "application/json" : {
                "examples" : {
                  "Error Response" : {
                    "value" : {
                      "type" : "https://example.com/probs/out-of-credit",
                      "title" : "You do not have enough credit.",
                      "detail" : "Your current balance is 30, but that costs 50.",
                      "instance" : "/account/12345/msgs/abc"
                    }
                  }
                },
                "schema" : {
                  "$ref" : "#/components/schemas/ProblemDetails"
                }
              }
            },
            "description" : "Unauthorized"
          },
          "404" : {
            "content" : {
              "application/json" : {
                "examples" : {
                  "Error Response" : {
                    "value" : {
                      "type" : "https://example.com/probs/out-of-credit",
                      "title" : "You do not have enough credit.",
                      "detail" : "Your current balance is 30, but that costs 50.",
                      "instance" : "/account/12345/msgs/abc"
                    }
                  }
                },
                "schema" : {
                  "$ref" : "#/components/schemas/ProblemDetails"
                }
              }
            },
            "description" : "Not Found"
          },
          "500" : {
            "content" : {
              "application/json" : {
                "examples" : {
                  "Error Response" : {
                    "value" : {
                      "type" : "https://example.com/probs/out-of-credit",
                      "title" : "You do not have enough credit.",
                      "detail" : "Your current balance is 30, but that costs 50.",
                      "instance" : "/account/12345/msgs/abc"
                    }
                  }
                },
                "schema" : {
                  "$ref" : "#/components/schemas/ProblemDetails"
                }
              }
            },
            "description" : "Internal Server Error"
          },
          "503" : {
            "content" : {
              "application/json" : {
                "examples" : {
                  "Error Response" : {
                    "value" : {
                      "type" : "https://example.com/probs/out-of-credit",
                      "title" : "You do not have enough credit.",
                      "detail" : "Your current balance is 30, but that costs 50.",
                      "instance" : "/account/12345/msgs/abc"
                    }
                  }
                },
                "schema" : {
                  "$ref" : "#/components/schemas/ProblemDetails"
                }
              }
            },
            "description" : "Service Unavailable"
          }
        },
        "summary" : "Get Reactions",
        "tags" : [ "Reaction" ]
      }
    },
    "/articles/{id}/reactions/{type}" : {
      "delete" : {
        "description" : "Remove an existing reaction to an article",
        "operationId" : "delete-reaction",
        "parameters" : [ {
          "description" : "The id of the article/page",
          "explode" : false,
          "in" : "path",
          "name" : "id",
          "required" : true,
          "schema" : {
            "type" : "string"
          },
          "style" : "simple"
        }, {
          "description" : "The type of reaction the user had",
          "explode" : false,
          "in" : "path",
          "name" : "type",
          "required" : true,
          "schema" : {
            "enum" : [ "LIKE", "DISLIKE" ],
            "example" : "LIKE",
            "type" : "string"
          },
          "style" : "simple"
        }, {
          "description" : "User Id sending request",
          "in" : "header",
          "name" : "userId",
          "required" : true,
          "schema" : {
            "example" : "PSUL",
            "type" : "string"
          }
        } ],
        "responses" : {
          "200" : {
            "content" : {
              "application/json" : {
                "examples" : {
                  "Sample Response" : {
                    "value" : {
                      "guid" : "123e4567-e89b-12d3-a456-426614174000"
                    }
                  }
                },
                "schema" : {
                  "$ref" : "#/components/schemas/UpdateSuccessResponse"
                }
              }
            },
            "description" : "OK"
          },
          "401" : {
            "content" : {
              "application/json" : {
                "examples" : {
                  "Error Response" : {
                    "value" : {
                      "type" : "https://example.com/probs/out-of-credit",
                      "title" : "You do not have enough credit.",
                      "detail" : "Your current balance is 30, but that costs 50.",
                      "instance" : "/account/12345/msgs/abc"
                    }
                  }
                },
                "schema" : {
                  "$ref" : "#/components/schemas/ProblemDetails"
                }
              }
            },
            "description" : "Unauthorized"
          },
          "404" : {
            "content" : {
              "application/json" : {
                "examples" : {
                  "Error Response" : {
                    "value" : {
                      "type" : "https://example.com/probs/out-of-credit",
                      "title" : "You do not have enough credit.",
                      "detail" : "Your current balance is 30, but that costs 50.",
                      "instance" : "/account/12345/msgs/abc"
                    }
                  }
                },
                "schema" : {
                  "$ref" : "#/components/schemas/ProblemDetails"
                }
              }
            },
            "description" : "Not Found"
          },
          "500" : {
            "content" : {
              "application/json" : {
                "examples" : {
                  "Error Response" : {
                    "value" : {
                      "type" : "https://example.com/probs/out-of-credit",
                      "title" : "You do not have enough credit.",
                      "detail" : "Your current balance is 30, but that costs 50.",
                      "instance" : "/account/12345/msgs/abc"
                    }
                  }
                },
                "schema" : {
                  "$ref" : "#/components/schemas/ProblemDetails"
                }
              }
            },
            "description" : "Internal Server Error"
          },
          "503" : {
            "content" : {
              "application/json" : {
                "examples" : {
                  "Error Response" : {
                    "value" : {
                      "type" : "https://example.com/probs/out-of-credit",
                      "title" : "You do not have enough credit.",
                      "detail" : "Your current balance is 30, but that costs 50.",
                      "instance" : "/account/12345/msgs/abc"
                    }
                  }
                },
                "schema" : {
                  "$ref" : "#/components/schemas/ProblemDetails"
                }
              }
            },
            "description" : "Service Unavailable"
          }
        },
        "summary" : "Remove Reaction",
        "tags" : [ "Reaction" ]
      },
      "get" : {
        "description" : "An end point that returns the reactions for an article/page to a client",
        "operationId" : "get-reaction",
        "parameters" : [ {
          "description" : "The id of the article/page",
          "explode" : false,
          "in" : "path",
          "name" : "id",
          "required" : true,
          "schema" : {
            "type" : "string"
          },
          "style" : "simple"
        }, {
          "description" : "The type of reaction the user had",
          "explode" : false,
          "in" : "path",
          "name" : "type",
          "required" : true,
          "schema" : {
            "enum" : [ "LIKE", "DISLIKE" ],
            "example" : "LIKE",
            "type" : "string"
          },
          "style" : "simple"
        }, {
          "description" : "User Id sending request",
          "in" : "header",
          "name" : "userId",
          "required" : true,
          "schema" : {
            "example" : "PSUL",
            "type" : "string"
          }
        } ],
        "responses" : {
          "200" : {
            "content" : {
              "application/json" : {
                "examples" : {
                  "Success Example" : {
                    "value" : {
                      "guid" : "123e4567-e89b-12d3-a456-426614174000",
                      "createdOn" : "2022-03-19 04:24:02.190",
                      "createdBy" : "PSUL",
                      "updatedOn" : "2022-10-12 14:01:13.000",
                      "updatedBy" : "PSUL",
                      "articleId" : "home",
                      "type" : "LIKE",
                      "count" : 548
                    }
                  }
                },
                "schema" : {
                  "$ref" : "#/components/schemas/get_reaction_200_response"
                }
              }
            },
            "description" : "Successful response to Get Reactions end point"
          },
          "401" : {
            "content" : {
              "application/json" : {
                "examples" : {
                  "Error Response" : {
                    "value" : {
                      "type" : "https://example.com/probs/out-of-credit",
                      "title" : "You do not have enough credit.",
                      "detail" : "Your current balance is 30, but that costs 50.",
                      "instance" : "/account/12345/msgs/abc"
                    }
                  }
                },
                "schema" : {
                  "$ref" : "#/components/schemas/ProblemDetails"
                }
              }
            },
            "description" : "Unauthorized"
          },
          "404" : {
            "content" : {
              "application/json" : {
                "examples" : {
                  "Error Response" : {
                    "value" : {
                      "type" : "https://example.com/probs/out-of-credit",
                      "title" : "You do not have enough credit.",
                      "detail" : "Your current balance is 30, but that costs 50.",
                      "instance" : "/account/12345/msgs/abc"
                    }
                  }
                },
                "schema" : {
                  "$ref" : "#/components/schemas/ProblemDetails"
                }
              }
            },
            "description" : "Not Found"
          },
          "500" : {
            "content" : {
              "application/json" : {
                "examples" : {
                  "Error Response" : {
                    "value" : {
                      "type" : "https://example.com/probs/out-of-credit",
                      "title" : "You do not have enough credit.",
                      "detail" : "Your current balance is 30, but that costs 50.",
                      "instance" : "/account/12345/msgs/abc"
                    }
                  }
                },
                "schema" : {
                  "$ref" : "#/components/schemas/ProblemDetails"
                }
              }
            },
            "description" : "Internal Server Error"
          },
          "503" : {
            "content" : {
              "application/json" : {
                "examples" : {
                  "Error Response" : {
                    "value" : {
                      "type" : "https://example.com/probs/out-of-credit",
                      "title" : "You do not have enough credit.",
                      "detail" : "Your current balance is 30, but that costs 50.",
                      "instance" : "/account/12345/msgs/abc"
                    }
                  }
                },
                "schema" : {
                  "$ref" : "#/components/schemas/ProblemDetails"
                }
              }
            },
            "description" : "Service Unavailable"
          }
        },
        "summary" : "Get Reaction",
        "tags" : [ "Reaction" ]
      },
      "post" : {
        "description" : "Add a new reaction to an article",
        "operationId" : "add-reaction",
        "parameters" : [ {
          "description" : "The id of the article/page",
          "explode" : false,
          "in" : "path",
          "name" : "id",
          "required" : true,
          "schema" : {
            "type" : "string"
          },
          "style" : "simple"
        }, {
          "description" : "The type of reaction the user had",
          "explode" : false,
          "in" : "path",
          "name" : "type",
          "required" : true,
          "schema" : {
            "enum" : [ "LIKE", "DISLIKE" ],
            "example" : "LIKE",
            "type" : "string"
          },
          "style" : "simple"
        }, {
          "description" : "User Id sending request",
          "in" : "header",
          "name" : "userId",
          "required" : true,
          "schema" : {
            "example" : "PSUL",
            "type" : "string"
          }
        } ],
        "responses" : {
          "200" : {
            "content" : {
              "application/json" : {
                "examples" : {
                  "Sample Response" : {
                    "value" : {
                      "guid" : "123e4567-e89b-12d3-a456-426614174000"
                    }
                  }
                },
                "schema" : {
                  "$ref" : "#/components/schemas/UpdateSuccessResponse"
                }
              }
            },
            "description" : "OK"
          },
          "401" : {
            "content" : {
              "application/json" : {
                "examples" : {
                  "Error Response" : {
                    "value" : {
                      "type" : "https://example.com/probs/out-of-credit",
                      "title" : "You do not have enough credit.",
                      "detail" : "Your current balance is 30, but that costs 50.",
                      "instance" : "/account/12345/msgs/abc"
                    }
                  }
                },
                "schema" : {
                  "$ref" : "#/components/schemas/ProblemDetails"
                }
              }
            },
            "description" : "Unauthorized"
          },
          "404" : {
            "content" : {
              "application/json" : {
                "examples" : {
                  "Error Response" : {
                    "value" : {
                      "type" : "https://example.com/probs/out-of-credit",
                      "title" : "You do not have enough credit.",
                      "detail" : "Your current balance is 30, but that costs 50.",
                      "instance" : "/account/12345/msgs/abc"
                    }
                  }
                },
                "schema" : {
                  "$ref" : "#/components/schemas/ProblemDetails"
                }
              }
            },
            "description" : "Not Found"
          },
          "500" : {
            "content" : {
              "application/json" : {
                "examples" : {
                  "Error Response" : {
                    "value" : {
                      "type" : "https://example.com/probs/out-of-credit",
                      "title" : "You do not have enough credit.",
                      "detail" : "Your current balance is 30, but that costs 50.",
                      "instance" : "/account/12345/msgs/abc"
                    }
                  }
                },
                "schema" : {
                  "$ref" : "#/components/schemas/ProblemDetails"
                }
              }
            },
            "description" : "Internal Server Error"
          },
          "503" : {
            "content" : {
              "application/json" : {
                "examples" : {
                  "Error Response" : {
                    "value" : {
                      "type" : "https://example.com/probs/out-of-credit",
                      "title" : "You do not have enough credit.",
                      "detail" : "Your current balance is 30, but that costs 50.",
                      "instance" : "/account/12345/msgs/abc"
                    }
                  }
                },
                "schema" : {
                  "$ref" : "#/components/schemas/ProblemDetails"
                }
              }
            },
            "description" : "Service Unavailable"
          }
        },
        "summary" : "Add Reaction",
        "tags" : [ "Reaction" ]
      }
    }
  },
  "components" : {
    "parameters" : {
      "userId" : {
        "description" : "User Id sending request",
        "in" : "header",
        "name" : "userId",
        "required" : true,
        "schema" : {
          "example" : "PSUL",
          "type" : "string"
        }
      }
    },
    "requestBodies" : { },
    "responses" : {
      "GetReactionsResponse" : {
        "content" : {
          "application/json" : {
            "examples" : {
              "Success Example" : {
                "value" : {
                  "guid" : "123e4567-e89b-12d3-a456-426614174000",
                  "createdOn" : "2022-03-19 04:24:02.190",
                  "createdBy" : "PSUL",
                  "updatedOn" : "2022-10-12 14:01:13.000",
                  "updatedBy" : "PSUL",
                  "articleId" : "home",
                  "reactions" : [ {
                    "type" : "LIKE",
                    "count" : 548
                  } ]
                }
              }
            },
            "schema" : {
              "$ref" : "#/components/schemas/get_reactions_200_response"
            }
          }
        },
        "description" : "Successful response to Get Reactions end point"
      },
      "GetReactionResponse" : {
        "content" : {
          "application/json" : {
            "examples" : {
              "Success Example" : {
                "value" : {
                  "guid" : "123e4567-e89b-12d3-a456-426614174000",
                  "createdOn" : "2022-03-19 04:24:02.190",
                  "createdBy" : "PSUL",
                  "updatedOn" : "2022-10-12 14:01:13.000",
                  "updatedBy" : "PSUL",
                  "articleId" : "home",
                  "type" : "LIKE",
                  "count" : 548
                }
              }
            },
            "schema" : {
              "$ref" : "#/components/schemas/get_reaction_200_response"
            }
          }
        },
        "description" : "Successful response to Get Reactions end point"
      }
    },
    "schemas" : {
      "ReactionDetail" : {
        "properties" : {
          "type" : {
            "default" : "LIKE",
            "enum" : [ "LIKE", "DISLIKE" ],
            "example" : "LIKE",
            "type" : "string"
          },
          "count" : {
            "example" : 548,
            "minimum" : 0,
            "type" : "integer"
          }
        },
        "required" : [ "count", "type" ],
        "title" : "ReactionDetail",
        "type" : "object",
        "x-stoplight" : {
          "id" : "eaea51555be8e"
        }
      },
      "RecordBase" : {
        "description" : "The minimum model fields shared by all data stored in the database",
        "properties" : {
          "guid" : {
            "description" : "The `guid` associated with the record",
            "example" : "123e4567-e89b-12d3-a456-426614174000",
            "format" : "uuid",
            "title" : "Guid",
            "type" : "string",
            "x-stoplight" : {
              "id" : "rxw5bcg38wwhi"
            },
            "x-examples" : {
              "Sample Guid" : "123e4567-e89b-12d3-a456-426614174000"
            }
          },
          "createdOn" : {
            "format" : "date-time",
            "type" : "string"
          },
          "createdBy" : {
            "example" : "PSUL",
            "type" : "string"
          },
          "updatedOn" : {
            "format" : "date-time",
            "type" : "string"
          },
          "updatedBy" : {
            "example" : "PSUL",
            "type" : "string"
          }
        },
        "required" : [ "createdBy", "createdOn", "guid" ],
        "title" : "RecordBase",
        "type" : "object",
        "x-stoplight" : {
          "id" : "426vq5mn5uary"
        },
        "x-examples" : {
          "Sample Record" : {
            "guid" : "123e4567-e89b-12d3-a456-426614174000",
            "createdOn" : "2022-03-19 04:24:02.190",
            "createdBy" : "PSUL",
            "updatedOn" : "2022-10-12 14:01:13.000",
            "updatedBy" : "PSUL"
          }
        }
      },
      "Guid" : {
        "description" : "The `guid` associated with the record",
        "example" : "123e4567-e89b-12d3-a456-426614174000",
        "format" : "uuid",
        "title" : "Guid",
        "type" : "string",
        "x-stoplight" : {
          "id" : "rxw5bcg38wwhi"
        },
        "x-examples" : {
          "Sample Guid" : "123e4567-e89b-12d3-a456-426614174000"
        }
      },
      "ProblemDetails" : {
        "description" : "A model for API errors inline with the [RFC 7807](https://www.rfc-editor.org/rfc/rfc7807) specification.",
        "properties" : {
          "type" : {
            "default" : "about:blank",
            "description" : "A URI reference [RFC3986](https://www.rfc-editor.org/rfc/rfc3986) that identifies the problem type. This specification encourages that, when dereferenced, it provide human-readable documentation for the problem type (e.g., using HTML [W3C.REC-html5-20141028](https://www.rfc-editor.org/rfc/rfc7807#ref-W3C.REC-html5-20141028)). When this member is not present, its value is assumed to be `about:blank`.",
            "example" : "https://example.com/probs/out-of-credit",
            "type" : "string"
          },
          "title" : {
            "default" : "An error occurred processing your request.",
            "description" : "A short, human-readable summary of the problem type. It **SHOULD NOT** change from occurrence to occurrence of the pro**blem, except for purposes of localization (e.g., using proactive content negotiation; see [RFC7231, Section 3.4](https://www.rfc-editor.org/rfc/rfc7231#section-3.4)).",
            "example" : "You do not have enough credit.",
            "type" : "string"
          },
          "detail" : {
            "description" : "A human-readable explanation specific to this occurrence of the problem.",
            "example" : "Your current balance is 30, but that costs 50.",
            "type" : "string"
          },
          "instance" : {
            "description" : "A URI reference that identifies the specific occurrence of the problem. It may or may not yield further information if dereferenced.",
            "example" : "/account/12345/msgs/abc",
            "type" : "string"
          }
        },
        "required" : [ "type" ],
        "title" : "ProblemDetails",
        "type" : "object",
        "x-stoplight" : {
          "id" : "9o873j87rv4nb"
        },
        "x-examples" : {
          "Sample Response" : {
            "type" : "about:blank",
            "title" : "An error occurred processing your request.",
            "detail" : "Your current balance is 30, but that costs 50.",
            "instance" : "/account/12345/msgs/abc"
          }
        }
      },
      "UpdateSuccessResponse" : {
        "description" : "A response returned from the server when data is successfully updated",
        "example" : {
          "guid" : "123e4567-e89b-12d3-a456-426614174000"
        },
        "properties" : {
          "guid" : {
            "description" : "The `guid` associated with the record",
            "example" : "123e4567-e89b-12d3-a456-426614174000",
            "format" : "uuid",
            "title" : "Guid",
            "type" : "string",
            "x-stoplight" : {
              "id" : "rxw5bcg38wwhi"
            },
            "x-examples" : {
              "Sample Guid" : "123e4567-e89b-12d3-a456-426614174000"
            }
          }
        },
        "required" : [ "guid" ],
        "title" : "UpdateSuccessResponse",
        "type" : "object",
        "x-stoplight" : {
          "id" : "bnmwekvdvhi5z"
        },
        "x-examples" : {
          "Sample Response" : {
            "guid" : "123e4567-e89b-12d3-a456-426614174000"
          }
        }
      },
      "get_reactions_200_response_allOf" : {
        "properties" : {
          "articleId" : {
            "description" : "The id of the article/page",
            "example" : "home",
            "type" : "string"
          },
          "reactions" : {
            "description" : "The list of reactions for the specified article ",
            "items" : {
              "$ref" : "#/components/schemas/ReactionDetail"
            },
            "type" : "array"
          }
        },
        "required" : [ "articleId", "reactions" ],
        "type" : "object"
      },
      "get_reactions_200_response" : {
        "allOf" : [ {
          "$ref" : "#/components/schemas/RecordBase"
        }, {
          "$ref" : "#/components/schemas/get_reactions_200_response_allOf"
        } ]
      },
      "get_reaction_200_response_allOf_allOf" : {
        "properties" : {
          "articleId" : {
            "description" : "The id of the article/page",
            "example" : "home",
            "type" : "string"
          }
        },
        "required" : [ "articleId" ],
        "type" : "object"
      },
      "get_reaction_200_response_allOf" : {
        "allOf" : [ {
          "$ref" : "#/components/schemas/get_reaction_200_response_allOf_allOf"
        }, {
          "$ref" : "#/components/schemas/ReactionDetail"
        } ]
      },
      "get_reaction_200_response" : {
        "allOf" : [ {
          "$ref" : "#/components/schemas/RecordBase"
        }, {
          "$ref" : "#/components/schemas/get_reaction_200_response_allOf"
        } ]
      }
    },
    "securitySchemes" : {
      "bearer-token" : {
        "description" : "A request header containing the JSON web token (JWT) provided by the IDM service in a cookie when the user signed into the application. This JWT contains the current user's encoded `SiteMinder` entitlements.",
        "scheme" : "bearer",
        "type" : "http"
      }
    }
  },
  "x-stoplight" : {
    "id" : "1121s8nqejp11"
  },
  "x-all-of-name" : "DTO_AllOf",
  "x-one-of-name" : "DTO_OneOf"
}
