{
  "openapi" : "3.0.0",
  "info" : {
    "contact" : {
      "email" : "Patrick.Joseph.Sullivan@protonmail.com",
      "name" : "Patrick Sullivan",
      "url" : "https://sullivanpj.github.io/open-system/services/contact"
    },
    "description" : "A collection of APIs used to get and set contact related data ",
    "license" : {
      "name" : "BSD 2-Clause License",
      "url" : "https://opensource.org/licenses/BSD-2-Clause"
    },
    "termsOfService" : "https://sullivanpj.github.io/open-system/services/contact",
    "title" : "Contact APIs",
    "version" : "1"
  },
  "servers" : [ {
    "description" : "Local Development",
    "url" : "http://localhost:5000"
  } ],
  "tags" : [ {
    "name" : "Contact"
  } ],
  "paths" : {
    "/requests" : {
      "get" : {
        "description" : "An end point that returns the list of contact requests",
        "operationId" : "get-contact-requests",
        "parameters" : [ {
          "description" : "The id of the current user sending the request",
          "in" : "header",
          "name" : "userId",
          "required" : true,
          "schema" : {
            "type" : "string"
          }
        } ],
        "responses" : {
          "200" : {
            "content" : {
              "application/json" : {
                "schema" : {
                  "items" : {
                    "$ref" : "#/components/schemas/Contact"
                  },
                  "type" : "array"
                }
              }
            },
            "description" : "Successful response to Get Users end point"
          },
          "401" : {
            "content" : {
              "application/json" : {
                "examples" : {
                  "Error Response" : {
                    "value" : {
                      "type" : "https://example.com/probs/out-of-credit",
                      "title" : "You do not have enough credit.",
                      "detail" : "Your current balance is 30, but that costs 50.",
                      "instance" : "/account/12345/msgs/abc"
                    }
                  }
                },
                "schema" : {
                  "$ref" : "#/components/schemas/ProblemDetails"
                }
              }
            },
            "description" : "Unauthorized"
          },
          "404" : {
            "content" : {
              "application/json" : {
                "examples" : {
                  "Error Response" : {
                    "value" : {
                      "type" : "https://example.com/probs/out-of-credit",
                      "title" : "You do not have enough credit.",
                      "detail" : "Your current balance is 30, but that costs 50.",
                      "instance" : "/account/12345/msgs/abc"
                    }
                  }
                },
                "schema" : {
                  "$ref" : "#/components/schemas/ProblemDetails"
                }
              }
            },
            "description" : "Not Found"
          },
          "500" : {
            "content" : {
              "application/json" : {
                "examples" : {
                  "Error Response" : {
                    "value" : {
                      "type" : "https://example.com/probs/out-of-credit",
                      "title" : "You do not have enough credit.",
                      "detail" : "Your current balance is 30, but that costs 50.",
                      "instance" : "/account/12345/msgs/abc"
                    }
                  }
                },
                "schema" : {
                  "$ref" : "#/components/schemas/ProblemDetails"
                }
              }
            },
            "description" : "Internal Server Error"
          },
          "503" : {
            "content" : {
              "application/json" : {
                "examples" : {
                  "Error Response" : {
                    "value" : {
                      "type" : "https://example.com/probs/out-of-credit",
                      "title" : "You do not have enough credit.",
                      "detail" : "Your current balance is 30, but that costs 50.",
                      "instance" : "/account/12345/msgs/abc"
                    }
                  }
                },
                "schema" : {
                  "$ref" : "#/components/schemas/ProblemDetails"
                }
              }
            },
            "description" : "Service Unavailable"
          }
        },
        "summary" : "Get Contact Requests",
        "tags" : [ "Contact" ]
      }
    },
    "/requests/{id}" : {
      "get" : {
        "description" : "An end point that returns data for a specific user",
        "operationId" : "get-contact-request",
        "parameters" : [ {
          "description" : "The reason for the current contact request",
          "explode" : false,
          "in" : "path",
          "name" : "id",
          "required" : true,
          "schema" : {
            "format" : "uuid",
            "type" : "string"
          },
          "style" : "simple"
        }, {
          "description" : "The id of the current user sending the request",
          "in" : "header",
          "name" : "userId",
          "required" : true,
          "schema" : {
            "type" : "string"
          }
        } ],
        "responses" : {
          "200" : {
            "content" : {
              "application/json" : {
                "schema" : {
                  "$ref" : "#/components/schemas/Contact"
                }
              }
            },
            "description" : "Successful response to Get User end point"
          },
          "401" : {
            "content" : {
              "application/json" : {
                "examples" : {
                  "Error Response" : {
                    "value" : {
                      "type" : "https://example.com/probs/out-of-credit",
                      "title" : "You do not have enough credit.",
                      "detail" : "Your current balance is 30, but that costs 50.",
                      "instance" : "/account/12345/msgs/abc"
                    }
                  }
                },
                "schema" : {
                  "$ref" : "#/components/schemas/ProblemDetails"
                }
              }
            },
            "description" : "Unauthorized"
          },
          "404" : {
            "content" : {
              "application/json" : {
                "examples" : {
                  "Error Response" : {
                    "value" : {
                      "type" : "https://example.com/probs/out-of-credit",
                      "title" : "You do not have enough credit.",
                      "detail" : "Your current balance is 30, but that costs 50.",
                      "instance" : "/account/12345/msgs/abc"
                    }
                  }
                },
                "schema" : {
                  "$ref" : "#/components/schemas/ProblemDetails"
                }
              }
            },
            "description" : "Not Found"
          },
          "500" : {
            "content" : {
              "application/json" : {
                "examples" : {
                  "Error Response" : {
                    "value" : {
                      "type" : "https://example.com/probs/out-of-credit",
                      "title" : "You do not have enough credit.",
                      "detail" : "Your current balance is 30, but that costs 50.",
                      "instance" : "/account/12345/msgs/abc"
                    }
                  }
                },
                "schema" : {
                  "$ref" : "#/components/schemas/ProblemDetails"
                }
              }
            },
            "description" : "Internal Server Error"
          },
          "503" : {
            "content" : {
              "application/json" : {
                "examples" : {
                  "Error Response" : {
                    "value" : {
                      "type" : "https://example.com/probs/out-of-credit",
                      "title" : "You do not have enough credit.",
                      "detail" : "Your current balance is 30, but that costs 50.",
                      "instance" : "/account/12345/msgs/abc"
                    }
                  }
                },
                "schema" : {
                  "$ref" : "#/components/schemas/ProblemDetails"
                }
              }
            },
            "description" : "Service Unavailable"
          }
        },
        "summary" : "Get Contact Request",
        "tags" : [ "Contact" ]
      },
      "post" : {
        "description" : "Add a new contact request",
        "operationId" : "add-contact-request",
        "parameters" : [ {
          "description" : "The reason for the current contact request",
          "explode" : false,
          "in" : "path",
          "name" : "id",
          "required" : true,
          "schema" : {
            "format" : "uuid",
            "type" : "string"
          },
          "style" : "simple"
        }, {
          "description" : "The id of the current user sending the request",
          "in" : "header",
          "name" : "userId",
          "required" : true,
          "schema" : {
            "type" : "string"
          }
        } ],
        "requestBody" : {
          "$ref" : "#/components/requestBodies/AddContactRequest"
        },
        "responses" : {
          "200" : {
            "content" : {
              "application/json" : {
                "examples" : {
                  "Sample Response" : {
                    "value" : {
                      "guid" : "123e4567-e89b-12d3-a456-426614174000"
                    }
                  }
                },
                "schema" : {
                  "$ref" : "#/components/schemas/UpdateSuccessResponse"
                }
              }
            },
            "description" : "OK"
          },
          "401" : {
            "content" : {
              "application/json" : {
                "examples" : {
                  "Error Response" : {
                    "value" : {
                      "type" : "https://example.com/probs/out-of-credit",
                      "title" : "You do not have enough credit.",
                      "detail" : "Your current balance is 30, but that costs 50.",
                      "instance" : "/account/12345/msgs/abc"
                    }
                  }
                },
                "schema" : {
                  "$ref" : "#/components/schemas/ProblemDetails"
                }
              }
            },
            "description" : "Unauthorized"
          },
          "404" : {
            "content" : {
              "application/json" : {
                "examples" : {
                  "Error Response" : {
                    "value" : {
                      "type" : "https://example.com/probs/out-of-credit",
                      "title" : "You do not have enough credit.",
                      "detail" : "Your current balance is 30, but that costs 50.",
                      "instance" : "/account/12345/msgs/abc"
                    }
                  }
                },
                "schema" : {
                  "$ref" : "#/components/schemas/ProblemDetails"
                }
              }
            },
            "description" : "Not Found"
          },
          "500" : {
            "content" : {
              "application/json" : {
                "examples" : {
                  "Error Response" : {
                    "value" : {
                      "type" : "https://example.com/probs/out-of-credit",
                      "title" : "You do not have enough credit.",
                      "detail" : "Your current balance is 30, but that costs 50.",
                      "instance" : "/account/12345/msgs/abc"
                    }
                  }
                },
                "schema" : {
                  "$ref" : "#/components/schemas/ProblemDetails"
                }
              }
            },
            "description" : "Internal Server Error"
          },
          "503" : {
            "content" : {
              "application/json" : {
                "examples" : {
                  "Error Response" : {
                    "value" : {
                      "type" : "https://example.com/probs/out-of-credit",
                      "title" : "You do not have enough credit.",
                      "detail" : "Your current balance is 30, but that costs 50.",
                      "instance" : "/account/12345/msgs/abc"
                    }
                  }
                },
                "schema" : {
                  "$ref" : "#/components/schemas/ProblemDetails"
                }
              }
            },
            "description" : "Service Unavailable"
          }
        },
        "summary" : "Add Contact Request",
        "tags" : [ "Contact" ]
      }
    },
    "/subscriptions" : {
      "get" : {
        "description" : "An end point that returns a list of emails on the subscription list",
        "operationId" : "get-subscriptions",
        "parameters" : [ {
          "description" : "The id of the current user sending the request",
          "in" : "header",
          "name" : "userId",
          "required" : true,
          "schema" : {
            "type" : "string"
          }
        } ],
        "responses" : {
          "200" : {
            "content" : {
              "application/json" : {
                "schema" : {
                  "items" : {
                    "type" : "string"
                  },
                  "type" : "array"
                }
              }
            },
            "description" : "OK"
          },
          "401" : {
            "content" : {
              "application/json" : {
                "examples" : {
                  "Error Response" : {
                    "value" : {
                      "type" : "https://example.com/probs/out-of-credit",
                      "title" : "You do not have enough credit.",
                      "detail" : "Your current balance is 30, but that costs 50.",
                      "instance" : "/account/12345/msgs/abc"
                    }
                  }
                },
                "schema" : {
                  "$ref" : "#/components/schemas/ProblemDetails"
                }
              }
            },
            "description" : "Unauthorized"
          },
          "404" : {
            "content" : {
              "application/json" : {
                "examples" : {
                  "Error Response" : {
                    "value" : {
                      "type" : "https://example.com/probs/out-of-credit",
                      "title" : "You do not have enough credit.",
                      "detail" : "Your current balance is 30, but that costs 50.",
                      "instance" : "/account/12345/msgs/abc"
                    }
                  }
                },
                "schema" : {
                  "$ref" : "#/components/schemas/ProblemDetails"
                }
              }
            },
            "description" : "Not Found"
          },
          "500" : {
            "content" : {
              "application/json" : {
                "examples" : {
                  "Error Response" : {
                    "value" : {
                      "type" : "https://example.com/probs/out-of-credit",
                      "title" : "You do not have enough credit.",
                      "detail" : "Your current balance is 30, but that costs 50.",
                      "instance" : "/account/12345/msgs/abc"
                    }
                  }
                },
                "schema" : {
                  "$ref" : "#/components/schemas/ProblemDetails"
                }
              }
            },
            "description" : "Internal Server Error"
          },
          "503" : {
            "content" : {
              "application/json" : {
                "examples" : {
                  "Error Response" : {
                    "value" : {
                      "type" : "https://example.com/probs/out-of-credit",
                      "title" : "You do not have enough credit.",
                      "detail" : "Your current balance is 30, but that costs 50.",
                      "instance" : "/account/12345/msgs/abc"
                    }
                  }
                },
                "schema" : {
                  "$ref" : "#/components/schemas/ProblemDetails"
                }
              }
            },
            "description" : "Service Unavailable"
          }
        },
        "summary" : "Get Subscriptions",
        "tags" : [ "Contact" ]
      }
    },
    "/subscriptions/{email}" : {
      "delete" : {
        "description" : "Add an existing email address from the subcription list",
        "operationId" : "unsubscribe",
        "parameters" : [ {
          "description" : "The email of the subscription",
          "explode" : false,
          "in" : "path",
          "name" : "email",
          "required" : true,
          "schema" : {
            "example" : "example@abc.com",
            "format" : "email",
            "type" : "string"
          },
          "style" : "simple"
        } ],
        "responses" : {
          "200" : {
            "content" : {
              "application/json" : {
                "examples" : {
                  "Sample Response" : {
                    "value" : {
                      "guid" : "123e4567-e89b-12d3-a456-426614174000"
                    }
                  }
                },
                "schema" : {
                  "$ref" : "#/components/schemas/UpdateSuccessResponse"
                }
              }
            },
            "description" : "OK"
          },
          "401" : {
            "content" : {
              "application/json" : {
                "examples" : {
                  "Error Response" : {
                    "value" : {
                      "type" : "https://example.com/probs/out-of-credit",
                      "title" : "You do not have enough credit.",
                      "detail" : "Your current balance is 30, but that costs 50.",
                      "instance" : "/account/12345/msgs/abc"
                    }
                  }
                },
                "schema" : {
                  "$ref" : "#/components/schemas/ProblemDetails"
                }
              }
            },
            "description" : "Unauthorized"
          },
          "404" : {
            "content" : {
              "application/json" : {
                "examples" : {
                  "Error Response" : {
                    "value" : {
                      "type" : "https://example.com/probs/out-of-credit",
                      "title" : "You do not have enough credit.",
                      "detail" : "Your current balance is 30, but that costs 50.",
                      "instance" : "/account/12345/msgs/abc"
                    }
                  }
                },
                "schema" : {
                  "$ref" : "#/components/schemas/ProblemDetails"
                }
              }
            },
            "description" : "Not Found"
          },
          "500" : {
            "content" : {
              "application/json" : {
                "examples" : {
                  "Error Response" : {
                    "value" : {
                      "type" : "https://example.com/probs/out-of-credit",
                      "title" : "You do not have enough credit.",
                      "detail" : "Your current balance is 30, but that costs 50.",
                      "instance" : "/account/12345/msgs/abc"
                    }
                  }
                },
                "schema" : {
                  "$ref" : "#/components/schemas/ProblemDetails"
                }
              }
            },
            "description" : "Internal Server Error"
          },
          "503" : {
            "content" : {
              "application/json" : {
                "examples" : {
                  "Error Response" : {
                    "value" : {
                      "type" : "https://example.com/probs/out-of-credit",
                      "title" : "You do not have enough credit.",
                      "detail" : "Your current balance is 30, but that costs 50.",
                      "instance" : "/account/12345/msgs/abc"
                    }
                  }
                },
                "schema" : {
                  "$ref" : "#/components/schemas/ProblemDetails"
                }
              }
            },
            "description" : "Service Unavailable"
          }
        },
        "summary" : "Unsubscribe",
        "tags" : [ "Contact" ]
      },
      "get" : {
        "description" : "An end point that returns a boolean value indicating if the specified email is on the subscription list",
        "operationId" : "get-subscription",
        "parameters" : [ {
          "description" : "The email of the subscription",
          "explode" : false,
          "in" : "path",
          "name" : "email",
          "required" : true,
          "schema" : {
            "example" : "example@abc.com",
            "format" : "email",
            "type" : "string"
          },
          "style" : "simple"
        }, {
          "description" : "The id of the current user sending the request",
          "in" : "header",
          "name" : "userId",
          "required" : true,
          "schema" : {
            "type" : "string"
          }
        } ],
        "responses" : {
          "200" : {
            "content" : {
              "application/json" : {
                "schema" : {
                  "default" : false,
                  "description" : "A boolean value indicating if the specified email is subscribed",
                  "type" : "boolean"
                }
              }
            },
            "description" : "OK"
          },
          "401" : {
            "content" : {
              "application/json" : {
                "examples" : {
                  "Error Response" : {
                    "value" : {
                      "type" : "https://example.com/probs/out-of-credit",
                      "title" : "You do not have enough credit.",
                      "detail" : "Your current balance is 30, but that costs 50.",
                      "instance" : "/account/12345/msgs/abc"
                    }
                  }
                },
                "schema" : {
                  "$ref" : "#/components/schemas/ProblemDetails"
                }
              }
            },
            "description" : "Unauthorized"
          },
          "404" : {
            "content" : {
              "application/json" : {
                "examples" : {
                  "Error Response" : {
                    "value" : {
                      "type" : "https://example.com/probs/out-of-credit",
                      "title" : "You do not have enough credit.",
                      "detail" : "Your current balance is 30, but that costs 50.",
                      "instance" : "/account/12345/msgs/abc"
                    }
                  }
                },
                "schema" : {
                  "$ref" : "#/components/schemas/ProblemDetails"
                }
              }
            },
            "description" : "Not Found"
          },
          "500" : {
            "content" : {
              "application/json" : {
                "examples" : {
                  "Error Response" : {
                    "value" : {
                      "type" : "https://example.com/probs/out-of-credit",
                      "title" : "You do not have enough credit.",
                      "detail" : "Your current balance is 30, but that costs 50.",
                      "instance" : "/account/12345/msgs/abc"
                    }
                  }
                },
                "schema" : {
                  "$ref" : "#/components/schemas/ProblemDetails"
                }
              }
            },
            "description" : "Internal Server Error"
          },
          "503" : {
            "content" : {
              "application/json" : {
                "examples" : {
                  "Error Response" : {
                    "value" : {
                      "type" : "https://example.com/probs/out-of-credit",
                      "title" : "You do not have enough credit.",
                      "detail" : "Your current balance is 30, but that costs 50.",
                      "instance" : "/account/12345/msgs/abc"
                    }
                  }
                },
                "schema" : {
                  "$ref" : "#/components/schemas/ProblemDetails"
                }
              }
            },
            "description" : "Service Unavailable"
          }
        },
        "summary" : "Get Subscription",
        "tags" : [ "Contact" ]
      },
      "post" : {
        "description" : "Add a new email address to the subcription list",
        "operationId" : "subscribe",
        "parameters" : [ {
          "description" : "The email of the subscription",
          "explode" : false,
          "in" : "path",
          "name" : "email",
          "required" : true,
          "schema" : {
            "example" : "example@abc.com",
            "format" : "email",
            "type" : "string"
          },
          "style" : "simple"
        }, {
          "description" : "The id of the current user sending the request",
          "in" : "header",
          "name" : "userId",
          "required" : true,
          "schema" : {
            "type" : "string"
          }
        } ],
        "requestBody" : {
          "$ref" : "#/components/requestBodies/AddContactRequest"
        },
        "responses" : {
          "200" : {
            "content" : {
              "application/json" : {
                "examples" : {
                  "Sample Response" : {
                    "value" : {
                      "guid" : "123e4567-e89b-12d3-a456-426614174000"
                    }
                  }
                },
                "schema" : {
                  "$ref" : "#/components/schemas/UpdateSuccessResponse"
                }
              }
            },
            "description" : "OK"
          },
          "401" : {
            "content" : {
              "application/json" : {
                "examples" : {
                  "Error Response" : {
                    "value" : {
                      "type" : "https://example.com/probs/out-of-credit",
                      "title" : "You do not have enough credit.",
                      "detail" : "Your current balance is 30, but that costs 50.",
                      "instance" : "/account/12345/msgs/abc"
                    }
                  }
                },
                "schema" : {
                  "$ref" : "#/components/schemas/ProblemDetails"
                }
              }
            },
            "description" : "Unauthorized"
          },
          "404" : {
            "content" : {
              "application/json" : {
                "examples" : {
                  "Error Response" : {
                    "value" : {
                      "type" : "https://example.com/probs/out-of-credit",
                      "title" : "You do not have enough credit.",
                      "detail" : "Your current balance is 30, but that costs 50.",
                      "instance" : "/account/12345/msgs/abc"
                    }
                  }
                },
                "schema" : {
                  "$ref" : "#/components/schemas/ProblemDetails"
                }
              }
            },
            "description" : "Not Found"
          },
          "500" : {
            "content" : {
              "application/json" : {
                "examples" : {
                  "Error Response" : {
                    "value" : {
                      "type" : "https://example.com/probs/out-of-credit",
                      "title" : "You do not have enough credit.",
                      "detail" : "Your current balance is 30, but that costs 50.",
                      "instance" : "/account/12345/msgs/abc"
                    }
                  }
                },
                "schema" : {
                  "$ref" : "#/components/schemas/ProblemDetails"
                }
              }
            },
            "description" : "Internal Server Error"
          },
          "503" : {
            "content" : {
              "application/json" : {
                "examples" : {
                  "Error Response" : {
                    "value" : {
                      "type" : "https://example.com/probs/out-of-credit",
                      "title" : "You do not have enough credit.",
                      "detail" : "Your current balance is 30, but that costs 50.",
                      "instance" : "/account/12345/msgs/abc"
                    }
                  }
                },
                "schema" : {
                  "$ref" : "#/components/schemas/ProblemDetails"
                }
              }
            },
            "description" : "Service Unavailable"
          }
        },
        "summary" : "Subscribe",
        "tags" : [ "Contact" ]
      }
    }
  },
  "components" : {
    "parameters" : {
      "type" : {
        "description" : "The type of the user",
        "explode" : true,
        "in" : "query",
        "name" : "type",
        "required" : false,
        "schema" : {
          "enum" : [ "guest", "internal", "external" ],
          "example" : "guest",
          "type" : "string"
        },
        "style" : "form"
      },
      "userId" : {
        "description" : "The id of the current user sending the request",
        "in" : "header",
        "name" : "userId",
        "required" : true,
        "schema" : {
          "type" : "string"
        }
      }
    },
    "requestBodies" : {
      "AddContactRequest" : {
        "content" : {
          "application/json" : {
            "schema" : {
              "$ref" : "#/components/schemas/ContactDetail"
            }
          }
        }
      }
    },
    "responses" : {
      "GetContactsResponse" : {
        "content" : {
          "application/json" : {
            "schema" : {
              "items" : {
                "$ref" : "#/components/schemas/Contact"
              },
              "type" : "array"
            }
          }
        },
        "description" : "Successful response to Get Users end point"
      },
      "GetContactResponse" : {
        "content" : {
          "application/json" : {
            "schema" : {
              "$ref" : "#/components/schemas/Contact"
            }
          }
        },
        "description" : "Successful response to Get User end point"
      }
    },
    "schemas" : {
      "Contact" : {
        "allOf" : [ {
          "$ref" : "#/components/schemas/RecordBase"
        }, {
          "$ref" : "#/components/schemas/ContactDetail"
        } ],
        "type" : "object"
      },
      "ContactDetail" : {
        "description" : "",
        "properties" : {
          "firstName" : {
            "type" : "string"
          },
          "lastName" : {
            "type" : "string"
          },
          "phoneNumber" : {
            "type" : "string"
          },
          "email" : {
            "description" : "The email address of the contact",
            "format" : "email",
            "type" : "string"
          },
          "reason" : {
            "default" : "business",
            "description" : "The type of contact request",
            "enum" : [ "business", "question", "casual", "other" ],
            "example" : "business",
            "type" : "string"
          },
          "details" : {
            "type" : "string"
          },
          "url" : {
            "format" : "uri",
            "type" : "string"
          },
          "isSubscribed" : {
            "default" : true,
            "type" : "boolean"
          }
        },
        "required" : [ "email", "isSubscribed" ],
        "title" : "ContactDetail",
        "type" : "object",
        "x-stoplight" : {
          "id" : "78659ef055685"
        }
      },
      "ProblemDetails" : {
        "description" : "A model for API errors inline with the [RFC 7807](https://www.rfc-editor.org/rfc/rfc7807) specification.",
        "properties" : {
          "type" : {
            "default" : "about:blank",
            "description" : "A URI reference [RFC3986](https://www.rfc-editor.org/rfc/rfc3986) that identifies the problem type. This specification encourages that, when dereferenced, it provide human-readable documentation for the problem type (e.g., using HTML [W3C.REC-html5-20141028](https://www.rfc-editor.org/rfc/rfc7807#ref-W3C.REC-html5-20141028)). When this member is not present, its value is assumed to be `about:blank`.",
            "example" : "https://example.com/probs/out-of-credit",
            "type" : "string"
          },
          "title" : {
            "default" : "An error occurred processing your request.",
            "description" : "A short, human-readable summary of the problem type. It **SHOULD NOT** change from occurrence to occurrence of the pro**blem, except for purposes of localization (e.g., using proactive content negotiation; see [RFC7231, Section 3.4](https://www.rfc-editor.org/rfc/rfc7231#section-3.4)).",
            "example" : "You do not have enough credit.",
            "type" : "string"
          },
          "detail" : {
            "description" : "A human-readable explanation specific to this occurrence of the problem.",
            "example" : "Your current balance is 30, but that costs 50.",
            "type" : "string"
          },
          "instance" : {
            "description" : "A URI reference that identifies the specific occurrence of the problem. It may or may not yield further information if dereferenced.",
            "example" : "/account/12345/msgs/abc",
            "type" : "string"
          }
        },
        "required" : [ "type" ],
        "title" : "ProblemDetails",
        "type" : "object",
        "x-stoplight" : {
          "id" : "9o873j87rv4nb"
        },
        "x-examples" : {
          "Sample Response" : {
            "type" : "about:blank",
            "title" : "An error occurred processing your request.",
            "detail" : "Your current balance is 30, but that costs 50.",
            "instance" : "/account/12345/msgs/abc"
          }
        }
      },
      "UpdateSuccessResponse" : {
        "description" : "A response returned from the server when data is successfully updated",
        "example" : {
          "guid" : "123e4567-e89b-12d3-a456-426614174000"
        },
        "properties" : {
          "guid" : {
            "description" : "The `guid` associated with the record",
            "example" : "123e4567-e89b-12d3-a456-426614174000",
            "format" : "uuid",
            "title" : "Guid",
            "type" : "string",
            "x-stoplight" : {
              "id" : "rxw5bcg38wwhi"
            },
            "x-examples" : {
              "Sample Guid" : "123e4567-e89b-12d3-a456-426614174000"
            }
          }
        },
        "required" : [ "guid" ],
        "title" : "UpdateSuccessResponse",
        "type" : "object",
        "x-stoplight" : {
          "id" : "bnmwekvdvhi5z"
        },
        "x-examples" : {
          "Sample Response" : {
            "guid" : "123e4567-e89b-12d3-a456-426614174000"
          }
        }
      },
      "Guid" : {
        "description" : "The `guid` associated with the record",
        "example" : "123e4567-e89b-12d3-a456-426614174000",
        "format" : "uuid",
        "title" : "Guid",
        "type" : "string",
        "x-stoplight" : {
          "id" : "rxw5bcg38wwhi"
        },
        "x-examples" : {
          "Sample Guid" : "123e4567-e89b-12d3-a456-426614174000"
        }
      },
      "RecordBase" : {
        "description" : "The minimum model fields shared by all data stored in the database",
        "properties" : {
          "guid" : {
            "description" : "The `guid` associated with the record",
            "example" : "123e4567-e89b-12d3-a456-426614174000",
            "format" : "uuid",
            "title" : "Guid",
            "type" : "string",
            "x-stoplight" : {
              "id" : "rxw5bcg38wwhi"
            },
            "x-examples" : {
              "Sample Guid" : "123e4567-e89b-12d3-a456-426614174000"
            }
          },
          "createdOn" : {
            "format" : "date-time",
            "type" : "string"
          },
          "createdBy" : {
            "example" : "PSUL",
            "type" : "string"
          },
          "updatedOn" : {
            "format" : "date-time",
            "type" : "string"
          },
          "updatedBy" : {
            "example" : "PSUL",
            "type" : "string"
          }
        },
        "required" : [ "createdBy", "createdOn", "guid" ],
        "title" : "RecordBase",
        "type" : "object",
        "x-stoplight" : {
          "id" : "426vq5mn5uary"
        },
        "x-examples" : {
          "Sample Record" : {
            "guid" : "123e4567-e89b-12d3-a456-426614174000",
            "createdOn" : "2022-03-19 04:24:02.190",
            "createdBy" : "PSUL",
            "updatedOn" : "2022-10-12 14:01:13.000",
            "updatedBy" : "PSUL"
          }
        }
      }
    },
    "securitySchemes" : { }
  },
  "x-stoplight" : {
    "id" : "2a667a1quawfq"
  },
  "x-all-of-name" : "DTO_AllOf",
  "x-one-of-name" : "DTO_OneOf"
}
