{
  "openapi": "3.0.0",
  "x-stoplight": {
    "id": "cd21s8nqejpjn"
  },
  "info": {
    "title": "Message",
    "version": "1.0",
    "description": "A collection of message APIs used by the Open System repository",
    "contact": {
      "name": "Patrick Sullivan",
      "email": "Patrick.Sullivan@broadridge.com",
      "url": "https://sullivanpj.github.io/open-system/services/message"
    },
    "termsOfService": "https://sullivanpj.github.io/open-system/services/message"
  },
  "servers": [
    {
      "url": "http://localhost:3000/messages",
      "description": "Local Development"
    }
  ],
  "paths": {
    "/": {
      "parameters": [],
      "get": {
        "summary": "Get Message List",
        "operationId": "get-message-list",
        "responses": {
          "200": {
            "description": "OK",
            "content": {
              "application/json": {
                "schema": {
                  "type": "array",
                  "items": {
                    "$ref": "#/components/schemas/Message"
                  }
                },
                "examples": {
                  "Success Response": {
                    "value": [
                      {
                        "guid": "123e4567-e89b-12d3-a456-426614174000",
                        "createdOn": "2022-03-19 04:24:02.190",
                        "createdBy": "PSUL",
                        "updatedOn": "2022-10-12 14:01:13.000",
                        "updatedBy": "PSUL",
                        "message": "This message is displayed in the application",
                        "messageType": "FXL",
                        "messageNumber": 338296833,
                        "culture": "EN-US"
                      }
                    ]
                  }
                }
              }
            }
          },
          "401": {
            "description": "Unauthorized",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "../../shared/shared.api-spec.json#/components/schemas/ProblemDetails"
                },
                "examples": {
                  "Error Response": {
                    "value": {
                      "type": "about:blank",
                      "title": "An error occurred processing your request.",
                      "detail": "Your current balance is 30, but that costs 50.",
                      "instance": "/account/12345/msgs/abc"
                    }
                  }
                }
              }
            }
          },
          "404": {
            "description": "Not Found",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "../../shared/shared.api-spec.json#/components/schemas/ProblemDetails"
                },
                "examples": {
                  "Error Response": {
                    "value": {
                      "type": "https://example.com/probs/out-of-credit",
                      "title": "You do not have enough credit.",
                      "detail": "Your current balance is 30, but that costs 50.",
                      "instance": "/account/12345/msgs/abc"
                    }
                  }
                }
              }
            }
          },
          "500": {
            "description": "Internal Server Error",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "../../shared/shared.api-spec.json#/components/schemas/ProblemDetails"
                },
                "examples": {
                  "Error Response": {
                    "value": {
                      "type": "https://example.com/probs/out-of-credit",
                      "title": "You do not have enough credit.",
                      "detail": "Your current balance is 30, but that costs 50.",
                      "instance": "/account/12345/msgs/abc"
                    }
                  }
                }
              }
            }
          },
          "503": {
            "description": "Service Unavailable",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "../../shared/shared.api-spec.json#/components/schemas/ProblemDetails"
                },
                "examples": {
                  "Error Response": {
                    "value": {
                      "type": "https://example.com/probs/out-of-credit",
                      "title": "You do not have enough credit.",
                      "detail": "Your current balance is 30, but that costs 50.",
                      "instance": "/account/12345/msgs/abc"
                    }
                  }
                }
              }
            }
          }
        },
        "parameters": [
          {
            "schema": {
              "type": "string",
              "default": "FXL",
              "enum": [
                "FXL",
                "24  TRADING",
                "24 CORE",
                "24 GENERAL",
                "APPLICATION",
                "CLIENT",
                "TRADINGVALIDATION",
                "INTERNALVALIDATION"
              ],
              "example": "FXL"
            },
            "in": "query",
            "name": "messageType",
            "description": "The type of message to return",
            "required": true
          },
          {
            "schema": {
              "type": "integer",
              "minimum": 0,
              "maximum": 999999999
            },
            "in": "query",
            "name": "messageNumber",
            "description": "A specific message number to return"
          },
          {
            "$ref": "../../shared/shared.api-spec.json#/components/parameters/userId"
          }
        ],
        "description": "An end point that returns the system's message literals to a client",
        "tags": [
          "Message"
        ]
      },
      "post": {
        "summary": "Add Message",
        "operationId": "add-message",
        "responses": {
          "200": {
            "description": "OK",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "../../shared/shared.api-spec.json#/components/schemas/UpdateSuccessResponse"
                },
                "examples": {
                  "Success Response": {
                    "value": {
                      "guid": "123e4567-e89b-12d3-a456-426614174000"
                    }
                  }
                }
              }
            }
          },
          "401": {
            "description": "Unauthorized",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "../../shared/shared.api-spec.json#/components/schemas/ProblemDetails"
                },
                "examples": {
                  "Error Response": {
                    "value": {
                      "type": "https://example.com/probs/out-of-credit",
                      "title": "You do not have enough credit.",
                      "detail": "Your current balance is 30, but that costs 50.",
                      "instance": "/account/12345/msgs/abc"
                    }
                  }
                }
              }
            }
          },
          "404": {
            "description": "Not Found",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "../../shared/shared.api-spec.json#/components/schemas/ProblemDetails"
                },
                "examples": {
                  "Error Response": {
                    "value": {
                      "type": "https://example.com/probs/out-of-credit",
                      "title": "You do not have enough credit.",
                      "detail": "Your current balance is 30, but that costs 50.",
                      "instance": "/account/12345/msgs/abc"
                    }
                  }
                }
              }
            }
          },
          "500": {
            "description": "Internal Server Error",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "../../shared/shared.api-spec.json#/components/schemas/ProblemDetails"
                },
                "examples": {
                  "Error Response": {
                    "value": {
                      "type": "https://example.com/probs/out-of-credit",
                      "title": "You do not have enough credit.",
                      "detail": "Your current balance is 30, but that costs 50.",
                      "instance": "/account/12345/msgs/abc"
                    }
                  }
                }
              }
            }
          },
          "503": {
            "description": "Service Unavailable",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "../../shared/shared.api-spec.json#/components/schemas/ProblemDetails"
                },
                "examples": {
                  "Error Response": {
                    "value": {
                      "type": "https://example.com/probs/out-of-credit",
                      "title": "You do not have enough credit.",
                      "detail": "Your current balance is 30, but that costs 50.",
                      "instance": "/account/12345/msgs/abc"
                    }
                  }
                }
              }
            }
          }
        },
        "description": "Add new message record",
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "$ref": "#/components/schemas/MessageRequest"
              },
              "examples": {
                "Sample Request": {
                  "value": {
                    "message": "This message is displayed in the application",
                    "messageType": "FXL",
                    "messageNumber": 338296833,
                    "culture": "EN-US"
                  }
                }
              }
            },
            "application/javascript": {
              "schema": {
                "$ref": "#/components/schemas/Message"
              }
            }
          },
          "description": ""
        },
        "parameters": [
          {
            "$ref": "../../shared/shared.api-spec.json#/components/parameters/userId"
          }
        ],
        "tags": [
          "Message"
        ]
      }
    },
    "/{guid}": {
      "parameters": [
        {
          "$ref": "../../shared/shared.api-spec.json#/components/parameters/guid"
        }
      ],
      "get": {
        "summary": "Get Message",
        "operationId": "get-message",
        "responses": {
          "200": {
            "description": "OK",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/Message"
                },
                "examples": {
                  "Success Response": {
                    "value": {
                      "guid": "123e4567-e89b-12d3-a456-426614174000",
                      "createdOn": "2022-03-19 04:24:02.190",
                      "createdBy": "PSUL",
                      "updatedOn": "2022-10-12 14:01:13.000",
                      "updatedBy": "PSUL",
                      "message": "This message is displayed in the application",
                      "messageType": "FXL",
                      "messageNumber": 338296833,
                      "culture": "EN-US"
                    }
                  }
                }
              }
            }
          },
          "401": {
            "description": "Unauthorized",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "../../shared/shared.api-spec.json#/components/schemas/ProblemDetails"
                },
                "examples": {
                  "Error Response": {
                    "value": {
                      "type": "https://example.com/probs/out-of-credit",
                      "title": "You do not have enough credit.",
                      "detail": "Your current balance is 30, but that costs 50.",
                      "instance": "/account/12345/msgs/abc"
                    }
                  }
                }
              }
            }
          },
          "404": {
            "description": "Not Found",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "../../shared/shared.api-spec.json#/components/schemas/ProblemDetails"
                },
                "examples": {
                  "Error Response": {
                    "value": {
                      "type": "https://example.com/probs/out-of-credit",
                      "title": "You do not have enough credit.",
                      "detail": "Your current balance is 30, but that costs 50.",
                      "instance": "/account/12345/msgs/abc"
                    }
                  }
                }
              }
            }
          },
          "500": {
            "description": "Internal Server Error",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "../../shared/shared.api-spec.json#/components/schemas/ProblemDetails"
                },
                "examples": {
                  "Error Response": {
                    "value": {
                      "type": "https://example.com/probs/out-of-credit",
                      "title": "You do not have enough credit.",
                      "detail": "Your current balance is 30, but that costs 50.",
                      "instance": "/account/12345/msgs/abc"
                    }
                  }
                }
              }
            }
          },
          "503": {
            "description": "Service Unavailable",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "../../shared/shared.api-spec.json#/components/schemas/ProblemDetails"
                },
                "examples": {
                  "Error Response": {
                    "value": {
                      "type": "https://example.com/probs/out-of-credit",
                      "title": "You do not have enough credit.",
                      "detail": "Your current balance is 30, but that costs 50.",
                      "instance": "/account/12345/msgs/abc"
                    }
                  }
                }
              }
            }
          }
        },
        "parameters": [
          {
            "$ref": "../../shared/shared.api-spec.json#/components/parameters/userId"
          }
        ],
        "description": "An end point that returns the system's message literals to a client",
        "tags": [
          "Message"
        ]
      },
      "delete": {
        "summary": "Remove Message",
        "operationId": "delete-message",
        "responses": {
          "200": {
            "description": "OK",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "../../shared/shared.api-spec.json#/components/schemas/UpdateSuccessResponse"
                },
                "examples": {
                  "Success Response": {
                    "value": {
                      "guid": "123e4567-e89b-12d3-a456-426614174000"
                    }
                  }
                }
              }
            }
          },
          "401": {
            "description": "Unauthorized",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "../../shared/shared.api-spec.json#/components/schemas/ProblemDetails"
                },
                "examples": {
                  "Error Response": {
                    "value": {
                      "type": "https://example.com/probs/out-of-credit",
                      "title": "You do not have enough credit.",
                      "detail": "Your current balance is 30, but that costs 50.",
                      "instance": "/account/12345/msgs/abc"
                    }
                  }
                }
              }
            }
          },
          "404": {
            "description": "Not Found",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "../../shared/shared.api-spec.json#/components/schemas/ProblemDetails"
                },
                "examples": {
                  "Error Response": {
                    "value": {
                      "type": "https://example.com/probs/out-of-credit",
                      "title": "You do not have enough credit.",
                      "detail": "Your current balance is 30, but that costs 50.",
                      "instance": "/account/12345/msgs/abc"
                    }
                  }
                }
              }
            }
          },
          "500": {
            "description": "Internal Server Error",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "../../shared/shared.api-spec.json#/components/schemas/ProblemDetails"
                },
                "examples": {
                  "Error Response": {
                    "value": {
                      "type": "https://example.com/probs/out-of-credit",
                      "title": "You do not have enough credit.",
                      "detail": "Your current balance is 30, but that costs 50.",
                      "instance": "/account/12345/msgs/abc"
                    }
                  }
                }
              }
            }
          },
          "503": {
            "description": "Service Unavailable",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "../../shared/shared.api-spec.json#/components/schemas/ProblemDetails"
                },
                "examples": {
                  "Error Response": {
                    "value": {
                      "type": "https://example.com/probs/out-of-credit",
                      "title": "You do not have enough credit.",
                      "detail": "Your current balance is 30, but that costs 50.",
                      "instance": "/account/12345/msgs/abc"
                    }
                  }
                }
              }
            }
          }
        },
        "description": "Remove an existing message record",
        "parameters": [
          {
            "$ref": "../../shared/shared.api-spec.json#/components/parameters/userId"
          }
        ],
        "tags": [
          "Message"
        ]
      },
      "patch": {
        "summary": "Update Message",
        "operationId": "update-message",
        "responses": {
          "200": {
            "description": "OK",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "../../shared/shared.api-spec.json#/components/schemas/UpdateSuccessResponse"
                },
                "examples": {
                  "Success Response": {
                    "value": {
                      "guid": "123e4567-e89b-12d3-a456-426614174000"
                    }
                  }
                }
              }
            }
          },
          "401": {
            "description": "Unauthorized",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "../../shared/shared.api-spec.json#/components/schemas/ProblemDetails"
                },
                "examples": {
                  "Error Response": {
                    "value": {
                      "type": "https://example.com/probs/out-of-credit",
                      "title": "You do not have enough credit.",
                      "detail": "Your current balance is 30, but that costs 50.",
                      "instance": "/account/12345/msgs/abc"
                    }
                  }
                }
              }
            }
          },
          "404": {
            "description": "Not Found",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "../../shared/shared.api-spec.json#/components/schemas/ProblemDetails"
                },
                "examples": {
                  "Error Response": {
                    "value": {
                      "type": "https://example.com/probs/out-of-credit",
                      "title": "You do not have enough credit.",
                      "detail": "Your current balance is 30, but that costs 50.",
                      "instance": "/account/12345/msgs/abc"
                    }
                  }
                }
              }
            }
          },
          "500": {
            "description": "Internal Server Error",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "../../shared/shared.api-spec.json#/components/schemas/ProblemDetails"
                },
                "examples": {
                  "Error Response": {
                    "value": {
                      "type": "https://example.com/probs/out-of-credit",
                      "title": "You do not have enough credit.",
                      "detail": "Your current balance is 30, but that costs 50.",
                      "instance": "/account/12345/msgs/abc"
                    }
                  }
                }
              }
            }
          },
          "503": {
            "description": "Service Unavailable",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "../../shared/shared.api-spec.json#/components/schemas/ProblemDetails"
                },
                "examples": {
                  "Error Response": {
                    "value": {
                      "type": "https://example.com/probs/out-of-credit",
                      "title": "You do not have enough credit.",
                      "detail": "Your current balance is 30, but that costs 50.",
                      "instance": "/account/12345/msgs/abc"
                    }
                  }
                }
              }
            }
          }
        },
        "description": "Update an existing message record",
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "$ref": "#/components/schemas/MessageRequest"
              },
              "examples": {
                "Sample Request": {
                  "value": {
                    "message": "This message is displayed in the application",
                    "messageType": "FXL",
                    "messageNumber": 338296833,
                    "culture": "EN-US"
                  }
                }
              }
            }
          }
        },
        "parameters": [
          {
            "$ref": "../../shared/shared.api-spec.json#/components/parameters/userId"
          }
        ],
        "tags": [
          "Message"
        ]
      }
    }
  },
  "components": {
    "schemas": {
      "Message": {
        "title": "Message",
        "x-stoplight": {
          "id": "1uit484jxisd8"
        },
        "description": "A `Message` record returned from the server",
        "x-examples": {
          "Sample Message": {
            "guid": "123e4567-e89b-12d3-a456-426614174000",
            "createdOn": "2022-03-19 04:24:02.190",
            "createdBy": "PSUL",
            "updatedOn": "2022-10-12 14:01:13.000",
            "updatedBy": "PSUL",
            "message": "This message is displayed in the application",
            "messageType": "FXL",
            "messageNumber": 338296833,
            "culture": "EN-US"
          }
        },
        "allOf": [
          {
            "$ref": "../../shared/shared.api-spec.json#/components/schemas/RecordBase"
          },
          {
            "$ref": "#/components/schemas/MessageRequest"
          },
          {
            "type": "object",
            "properties": {
              "messageNumber": {
                "type": "integer",
                "example": 338296833,
                "minimum": 0,
                "maximum": 999999999
              }
            },
            "required": [
              "messageNumber"
            ]
          }
        ]
      },
      "MessageRequest": {
        "title": "Message Request",
        "x-stoplight": {
          "id": "1uit484jxisd8"
        },
        "description": "An object sent to the server in a request to add a new or edit an existing `Message`. ",
        "x-examples": {
          "Sample Message Request": {
            "message": "This message is displayed in the application",
            "messageType": "FXL",
            "messageNumber": 338296833,
            "culture": "EN-US"
          }
        },
        "type": "object",
        "properties": {
          "message": {
            "type": "string",
            "example": "This message is displayed in the application"
          },
          "messageType": {
            "type": "string",
            "enum": [
              "FXL",
              "24 CORE",
              "24 GENERAL",
              "APPLICATION",
              "CLIENT",
              "TRADINGVALIDATION",
              "INTERNALVALIDATION",
              "24 TRADING"
            ],
            "default": "FXL",
            "example": "FXL"
          },
          "messageNumber": {
            "type": "integer",
            "example": 338296833,
            "minimum": 0,
            "maximum": 999999999
          },
          "culture": {
            "type": "string",
            "default": "EN-US",
            "example": "EN-US",
            "enum": [
              "EN-US"
            ]
          }
        },
        "required": [
          "message",
          "messageType",
          "culture"
        ]
      }
    },
    "requestBodies": {},
    "responses": {
      "GetMessagesResponse": {
        "description": "Successful response to Get Messages end point",
        "content": {
          "application/json": {
            "schema": {
              "type": "array",
              "items": {
                "allOf": [
                  {
                    "$ref": "../../shared/shared.api-spec.json#/components/schemas/RecordBase"
                  },
                  {
                    "$ref": "#/components/schemas/Message"
                  }
                ]
              }
            },
            "examples": {
              "Success Response": {
                "value": [
                  {
                    "guid": "123e4567-e89b-12d3-a456-426614174000",
                    "createdOn": "2022-03-19 04:24:02.190",
                    "createdBy": "PSUL",
                    "updatedOn": "2022-10-12 14:01:13.000",
                    "updatedBy": "PSUL",
                    "message": "This message is displayed in the application",
                    "messageType": "FXL",
                    "messageNumber": 338296833,
                    "culture": "EN-US"
                  }
                ]
              }
            }
          }
        }
      }
    },
    "parameters": {},
    "securitySchemes": {
      "bearer-token": {
        "type": "http",
        "scheme": "bearer",
        "description": "A request header containing the JSON web token (JWT) provided by the IDM service in a cookie when the user signed into the application. This JWT contains the current user's encoded `SiteMinder` entitlements."
      }
    }
  },
  "tags": [
    {
      "name": "Message"
    }
  ],
  "x-all-of-name": "DTO_AllOf",
  "x-one-of-name": "DTO_OneOf"
}